<?php

use App\Models\MenuItem;
use Illuminate\Database\Migrations\Migration;

/**
 * Cocokkan foto asli ke SELURUH menu makanan (exact + fuzzy nama termirip).
 * Foto di-commit ke public/img/menu/pool (reusable, satu foto bisa dipakai
 * beberapa item). Kategori minuman sengaja dibiarkan tanpa foto (belum ada
 * sumber foto) sehingga memakai placeholder ikon yang elegan.
 * Idempotent: aman dijalankan ulang saat deploy.
 */
return new class extends Migration
{
    public function up(): void
    {
        $map = [
            'aneka-jajanan-pasar-cenil' => 'img/menu/pool/jajanan-pasar-cenil.jpg',
            'aneka-jajanan-pasar-dadar-jiwa' => 'img/menu/pool/jajanan-pasar-dadar-jiwa.jpg',
            'aneka-jajanan-pasar-gandus' => 'img/menu/pool/jajanan-pasar-lemper.jpg',
            'aneka-jajanan-pasar-klepon' => 'img/menu/pool/jajanan-pasar-lemper.jpg',
            'aneka-jajanan-pasar-lemper' => 'img/menu/pool/jajanan-pasar-lemper.jpg',
            'aneka-jajanan-pasar-lupis' => 'img/menu/pool/jajanan-pasar-lupis.jpg',
            'aneka-jajanan-pasar-ongol-ongol' => 'img/menu/pool/jajanan-pasar-lemper.jpg',
            'aneka-jajanan-pasar-risol' => 'img/menu/pool/jajanan-pasar-risol.jpg',
            'aneka-jajanan-pasar-sus-coklat' => 'img/menu/pool/jajanan-pasar-sus-coklat.jpg',
            'aneka-jajanan-pasar-sus-vanila' => 'img/menu/pool/jajanan-pasar-sus-vanila.jpg',
            'aneka-kue-basah-engkak-ketan' => 'img/menu/pool/jajanan-pasar-lapis-legit.jpg',
            'aneka-kue-basah-kojo' => 'img/menu/pool/jajanan-pasar-kojo.jpg',
            'aneka-kue-basah-kue-8-jam' => 'img/menu/pool/jajanan-pasar-8-jam.jpg',
            'aneka-kue-basah-lapis-legit' => 'img/menu/pool/jajanan-pasar-lapis-legit.jpg',
            'aneka-kue-basah-mak-suba' => 'img/menu/pool/jajanan-pasar-lapis-legit.jpg',
            'aneka-nasi-bakar-nasi-bakar-ati' => 'img/menu/pool/nasi-goreng-ati.jpg',
            'aneka-nasi-bakar-nasi-bakar-ayam-goreng' => 'img/menu/pool/nasi-bakar-ayam-goreng.jpg',
            'aneka-nasi-bakar-nasi-bakar-ayam-suir' => 'img/menu/pool/nasi-bakar-ayam-suir.jpg',
            'aneka-nasi-bakar-nasi-bakar-balado-dendeng' => 'img/menu/pool/nasi-goreng-dendeng.jpg',
            'aneka-nasi-bakar-nasi-bakar-cumi' => 'img/menu/pool/nasi-bakar-cumi-suir.jpg',
            'aneka-nasi-bakar-nasi-bakar-daging-sapi' => 'img/menu/pool/nasi-sapi-lada-hitam.jpg',
            'aneka-nasi-bakar-nasi-bakar-malbi' => 'img/menu/pool/nasi-goreng-malbi.jpg',
            'aneka-nasi-bakar-nasi-bakar-polos' => 'img/menu/pool/nasi-bakar-ayam-goreng.jpg',
            'aneka-nasi-bakar-nasi-bakar-rendang' => 'img/menu/pool/nasi-goreng-rendang.jpg',
            'aneka-nasi-bakar-nasi-bakar-udang-balado' => 'img/menu/pool/nasi-bakar-ayam-goreng.jpg',
            'aneka-pempek-adaan' => 'img/menu/pool/pempek-adaan.jpg',
            'aneka-pempek-keriting' => 'img/menu/pool/pempek-keriting.jpg',
            'aneka-pempek-lenjer-kecil' => 'img/menu/pool/pempek-lenjer-kecil.jpg',
            'aneka-pempek-model' => 'img/menu/pool/model-ikan.jpg',
            'aneka-pempek-pempek-kapal-selam' => 'img/menu/pool/pempek-telor-besar-atau-pempek-kapal-selam.jpg',
            'aneka-pempek-pempek-lenggang' => 'img/menu/pool/pempek-lenggang.jpg',
            'aneka-pempek-pempek-panggang' => 'img/menu/pool/pempek-panggang.jpg',
            'aneka-pempek-pistel' => 'img/menu/pool/pempek-pistel.jpg',
            'aneka-pempek-rujak-mie' => 'img/menu/pool/mie-goreng-ayam.jpg',
            'aneka-pempek-tahu' => 'img/menu/pool/aneka-pempek-kecil.jpg',
            'aneka-pempek-tekwan' => 'img/menu/pool/tekwan.jpg',
            'aneka-pempek-telur-kecil' => 'img/menu/pool/pempek-telor-kecil.jpg',
            'aneka-prasmanan-ayam-kalasan' => 'img/menu/pool/ayam-kalasan.jpg',
            'aneka-prasmanan-ayam-kalio' => 'img/menu/pool/nasi-minyak.jpg',
            'aneka-prasmanan-ayam-kare' => 'img/menu/pool/nasi-minyak.jpg',
            'aneka-prasmanan-ayam-semur' => 'img/menu/pool/nasi-minyak.jpg',
            'aneka-prasmanan-bihun' => 'img/menu/pool/nasi-minyak.jpg',
            'aneka-prasmanan-malbi-rendang-balado' => 'img/menu/pool/nasi-minyak.jpg',
            'aneka-prasmanan-mie-tumis' => 'img/menu/pool/mie-goreng-ayam.jpg',
            'aneka-prasmanan-nasi-minyak' => 'img/menu/pool/nasi-minyak.jpg',
            'aneka-prasmanan-pentul' => 'img/menu/pool/nasi-minyak.jpg',
            'aneka-prasmanan-perkedel' => 'img/menu/pool/nasi-minyak.jpg',
            'aneka-prasmanan-sambal-cenge' => 'img/menu/pool/udang-sambal-pete.jpg',
            'aneka-prasmanan-sambal-tempe' => 'img/menu/pool/udang-sambal-pete.jpg',
            'aneka-prasmanan-sate-ati' => 'img/menu/pool/nasi-goreng-ati.jpg',
            'aneka-prasmanan-sayur-buncis' => 'img/menu/pool/nasi-minyak.jpg',
            'aneka-prasmanan-sayur-capcai' => 'img/menu/pool/nasi-minyak.jpg',
            'aneka-prasmanan-telur-asam-manis' => 'img/menu/pool/ayam-asam-manis-juga.jpg',
            'aneka-prasmanan-telur-kalio' => 'img/menu/pool/nasi-minyak.jpg',
            'aneka-prasmanan-telur-kare' => 'img/menu/pool/nasi-minyak.jpg',
            'aneka-prasmanan-telur-sambal' => 'img/menu/pool/udang-sambal-pete.jpg',
            'aneka-prasmanan-telur-semur' => 'img/menu/pool/nasi-minyak.jpg',
            'aneka-prasmanan-tempe-bacem' => 'img/menu/pool/nasi-minyak.jpg',
            'aneka-prasmanan-tempe-kecap' => 'img/menu/pool/nasi-minyak.jpg',
            'aneka-roti-bakar-roti-bakar-coklat' => 'img/menu/pool/sarapan-pagi-roti-bakar-keju-coklat.jpg',
            'aneka-roti-bakar-roti-bakar-coklat-keju' => 'img/menu/pool/sarapan-pagi-roti-bakar-keju-coklat.jpg',
            'aneka-roti-bakar-roti-bakar-keju-susu' => 'img/menu/pool/sarapan-pagi-roti-bakar-keju-susu.jpg',
            'aneka-roti-bakar-roti-bakar-mentega-gula' => 'img/menu/pool/sarapan-pagi-roti-bakar-keju-coklat.jpg',
            'aneka-sarapan-pagi-burgo' => 'img/menu/pool/sarapan-pagi-burgo.jpg',
            'aneka-sarapan-pagi-celimpungan' => 'img/menu/pool/sarapan-pagi-celimpungan.jpg',
            'aneka-sarapan-pagi-lakso' => 'img/menu/pool/sarapan-pagi-nasi-uduk.jpg',
            'aneka-sarapan-pagi-lontong' => 'img/menu/pool/sarapan-pagi-lontong.jpg',
            'aneka-sarapan-pagi-nasi-uduk-ayam-goreng' => 'img/menu/pool/nasi-bakar-ayam-goreng.jpg',
            'aneka-sarapan-pagi-nasi-uduk-telur' => 'img/menu/pool/sarapan-pagi-nasi-uduk.jpg',
            'aneka-sayuran-brokoli-bawang-putih' => 'img/menu/pool/brokoli-bawang-putih.jpg',
            'aneka-sayuran-brokoli-cah-sapi' => 'img/menu/pool/brokoli-cah-sapi.jpg',
            'aneka-sayuran-brokoli-cah-sari-laut' => 'img/menu/pool/brokoli-cah-sari-laut.jpg',
            'aneka-sayuran-brokoli-jamur-sintake' => 'img/menu/pool/brokoli-jamur-sintake.jpg',
            'aneka-sayuran-buncis-cah-udang' => 'img/menu/pool/brokoli-cah-sapi.jpg',
            'aneka-sayuran-buncis-goreng' => 'img/menu/pool/brokoli-cah-sapi.jpg',
            'aneka-sayuran-buncis-tumis-ala-szechuan' => 'img/menu/pool/brokoli-cah-sapi.jpg',
            'aneka-sayuran-capcay' => 'img/menu/pool/brokoli-cah-sapi.jpg',
            'aneka-sayuran-kangkung-balacan' => 'img/menu/pool/kangkung-balacan.jpg',
            'aneka-sayuran-kangkung-bawang-putih' => 'img/menu/pool/kangkung-bawang-putih.jpg',
            'aneka-sayuran-toge-ikan-asin' => 'img/menu/pool/toge-ikan-asin.jpg',
            'ayam-ayam-bakar-bumbu-bali' => 'img/menu/pool/ayam-bakar-saos-madu.jpg',
            'ayam-ayam-bakar-bumbu-jahe' => 'img/menu/pool/ayam-bakar-saos-madu.jpg',
            'ayam-ayam-bakar-saos-madu' => 'img/menu/pool/ayam-bakar-saos-madu.jpg',
            'ayam-ayam-cabe-ijo' => 'img/menu/pool/ayam-cabe-ijo.jpg',
            'ayam-ayam-goreng-aceh' => 'img/menu/pool/ayam-goreng-aceh-1.jpg',
            'ayam-ayam-kalasan' => 'img/menu/pool/ayam-kalasan.jpg',
            'ayam-ayam-kluyuk' => 'img/menu/pool/ayam-kluyuk.jpg',
            'ayam-ayam-kungpao' => 'img/menu/pool/ayam-goreng-mentega.jpg',
            'ayam-ayam-lada-garam' => 'img/menu/pool/ayam-lada-garam.jpg',
            'ayam-ayam-saos-lemon' => 'img/menu/pool/ayam-saos-lemon.jpg',
            'ayam-ayam-saos-mentega' => 'img/menu/pool/ayam-goreng-mentega.jpg',
            'ayam-sate-ayam' => 'img/menu/pool/ayam-goreng-mentega.jpg',
            'bubur-mie-ayam-bubur-abon' => 'img/menu/pool/sarapan-pagi-bubur-abon.jpg',
            'bubur-mie-ayam-bubur-ayam' => 'img/menu/pool/sarapan-pagi-bubur-ayam.jpg',
            'bubur-mie-ayam-bubur-kacang-ijo' => 'img/menu/pool/sarapan-pagi-bubur-kacang-ijo.jpg',
            'bubur-mie-ayam-gohyong-ayam' => 'img/menu/pool/sarapan-pagi-bubur-ayam.jpg',
            'bubur-mie-ayam-indomie-goreng-biasa' => 'img/menu/pool/sarapan-pagi-bubur-ayam.jpg',
            'bubur-mie-ayam-indomie-goreng-telur' => 'img/menu/pool/sarapan-pagi-bubur-ayam.jpg',
            'bubur-mie-ayam-indomie-kari-ayam-biasa' => 'img/menu/pool/nasi-ayam-kari-cincang.jpg',
            'bubur-mie-ayam-indomie-kari-ayam-telur' => 'img/menu/pool/nasi-ayam-kari-cincang.jpg',
            'bubur-mie-ayam-mie-ayam' => 'img/menu/pool/mie-goreng-ayam.jpg',
            'bubur-mie-ayam-telur-setengah-matang' => 'img/menu/pool/sarapan-pagi-bubur-ayam.jpg',
            'cumi-cumi-bakar-bumbu-bali' => 'img/menu/pool/cumi-bakar-bumbu-bali.jpg',
            'cumi-cumi-bakar-bumbu-jahe' => 'img/menu/pool/cumi-bakar-bumbu-jahe.jpg',
            'cumi-cumi-bakar-saos-madu' => 'img/menu/pool/cumi-bakar-saos-madu.jpg',
            'cumi-cumi-crispy' => 'img/menu/pool/cumi-crispy.jpg',
            'cumi-cumi-lada-garam' => 'img/menu/pool/ayam-lada-garam.jpg',
            'cumi-cumi-pedas-manis' => 'img/menu/pool/cumi-pedas-manis.jpg',
            'cumi-cumi-saos-asam-manis' => 'img/menu/pool/ayam-asam-manis-juga.jpg',
            'cumi-cumi-saos-padang' => 'img/menu/pool/cumi-bakar-saos-madu.jpg',
            'cumi-cumi-saos-thai' => 'img/menu/pool/udang-saos-thai.jpg',
            'ikan-gurami-bakar-bumbu-bali' => 'img/menu/pool/cumi-bakar-bumbu-bali.jpg',
            'ikan-gurami-bakar-bumbu-jahe' => 'img/menu/pool/cumi-bakar-bumbu-jahe.jpg',
            'ikan-gurami-goreng-terbang' => 'img/menu/pool/cumi-bakar-bumbu-bali.jpg',
            'ikan-gurami-saos-madu' => 'img/menu/pool/cumi-bakar-saos-madu.jpg',
            'ikan-gurami-saos-padang' => 'img/menu/pool/cumi-bakar-bumbu-bali.jpg',
            'ikan-gurami-saos-pedas-manis' => 'img/menu/pool/cumi-pedas-manis.jpg',
            'ikan-ikan-filet-bakar-bumbu-bali' => 'img/menu/pool/cumi-bakar-bumbu-bali.jpg',
            'ikan-ikan-filet-bakar-bumbu-jahe' => 'img/menu/pool/cumi-bakar-bumbu-jahe.jpg',
            'ikan-ikan-filet-saos-madu' => 'img/menu/pool/cumi-bakar-saos-madu.jpg',
            'ikan-ikan-filet-saos-padang' => 'img/menu/pool/cumi-bakar-bumbu-bali.jpg',
            'ikan-ikan-filet-saos-pedas-manis' => 'img/menu/pool/cumi-pedas-manis.jpg',
            'ikan-ikan-gabus-dabu-dabu' => 'img/menu/pool/ayam-dabu-dabu.jpg',
            'nasi-goreng-mie-kwetiau-kwetiau-goreng-ayam' => 'img/menu/pool/kwetiau-goreng-sapi.jpg',
            'nasi-goreng-mie-kwetiau-kwetiau-goreng-sapi' => 'img/menu/pool/kwetiau-goreng-sapi.jpg',
            'nasi-goreng-mie-kwetiau-kwetiau-goreng-seafood' => 'img/menu/pool/kwetiau-goreng-seafood.jpg',
            'nasi-goreng-mie-kwetiau-mie-goreng-ayam-seafood' => 'img/menu/pool/mie-goreng-seafood.jpg',
            'nasi-goreng-mie-kwetiau-mie-goreng-special-ultah' => 'img/menu/pool/mie-goreng-spesial-ultah-juga.jpg',
            'nasi-goreng-mie-kwetiau-nasi-goreng-ati' => 'img/menu/pool/nasi-goreng-ati.jpg',
            'nasi-goreng-mie-kwetiau-nasi-goreng-dendeng' => 'img/menu/pool/nasi-goreng-dendeng.jpg',
            'nasi-goreng-mie-kwetiau-nasi-goreng-kampung' => 'img/menu/pool/nasi-goreng-kampung.jpg',
            'nasi-goreng-mie-kwetiau-nasi-goreng-malbi' => 'img/menu/pool/nasi-goreng-malbi.jpg',
            'nasi-goreng-mie-kwetiau-nasi-goreng-nanas' => 'img/menu/pool/nasi-goreng-kampung.jpg',
            'nasi-goreng-mie-kwetiau-nasi-goreng-polos' => 'img/menu/pool/nasi-goreng-kampung.jpg',
            'nasi-goreng-mie-kwetiau-nasi-goreng-rendang' => 'img/menu/pool/nasi-goreng-rendang.jpg',
            'nasi-goreng-mie-kwetiau-nasi-goreng-sapi-pete' => 'img/menu/pool/nasi-sapi-lada-hitam.jpg',
            'nasi-goreng-mie-kwetiau-nasi-goreng-tomyam' => 'img/menu/pool/nasi-goreng-kampung.jpg',
            'paket-pempek-1-cap-4-lenjer-besar' => 'img/menu/pool/pempek-lenjer-besar.jpg',
            'paket-pempek-1-cap-4-telur-besar' => 'img/menu/pool/pempek-telor-besar-atau-pempek-kapal-selam.jpg',
            'paket-pempek-1-cap-5-lenjer-besar' => 'img/menu/pool/pempek-lenjer-besar.jpg',
            'paket-pempek-1-cap-5-telur-besar' => 'img/menu/pool/pempek-telor-besar-atau-pempek-kapal-selam.jpg',
            'paket-pempek-1-cap-tekwan' => 'img/menu/pool/tekwan.jpg',
            'paket-pempek-botor-kerupuk-kemplang-goreng' => 'img/menu/pool/pempek-paketan-1.jpg',
            'paket-pempek-kerupuk-kemplang-panggang-gobang' => 'img/menu/pool/pempek-paketan-1.jpg',
            'paket-pempek-paket-100-pcs' => 'img/menu/pool/pempek-paketan-1.jpg',
            'paket-pempek-paket-125-pcs' => 'img/menu/pool/pempek-paketan-1.jpg',
            'paket-pempek-paket-25-pcs' => 'img/menu/pool/pempek-paketan-1.jpg',
            'paket-pempek-paket-250-pcs' => 'img/menu/pool/pempek-paketan-1.jpg',
            'paket-pempek-paket-30-pcs' => 'img/menu/pool/pempek-paketan-1.jpg',
            'paket-pempek-paket-40-pcs' => 'img/menu/pool/pempek-paketan-1.jpg',
            'paket-pempek-paket-50-pcs' => 'img/menu/pool/pempek-paketan-1.jpg',
            'paket-pempek-paket-60-pcs' => 'img/menu/pool/pempek-paketan-1.jpg',
            'paket-pempek-paket-70-pcs' => 'img/menu/pool/pempek-paketan-1.jpg',
            'paket-pempek-paket-75-pcs' => 'img/menu/pool/pempek-paketan-1.jpg',
            'paket-pempek-paket-85-pcs' => 'img/menu/pool/pempek-paketan-1.jpg',
            'pindang-brengkes-brengkes-gabus-tempoyak' => 'img/menu/pool/brengkes-gabus-tempoyak.jpg',
            'pindang-brengkes-brengkes-ikan-pedo' => 'img/menu/pool/pindang-patin.jpg',
            'pindang-brengkes-brengkes-patin-tempoyak' => 'img/menu/pool/brengkes-patin-tempoyak.jpg',
            'pindang-brengkes-brengkes-udang-tempoyak' => 'img/menu/pool/brengkes-gabus-tempoyak.jpg',
            'pindang-brengkes-pindang-ayam' => 'img/menu/pool/pindang-gabus-juga.jpg',
            'pindang-brengkes-pindang-ikan-gabus' => 'img/menu/pool/pindang-gabus-juga.jpg',
            'pindang-brengkes-pindang-kerupuk' => 'img/menu/pool/pindang-kerupuk.jpg',
            'pindang-brengkes-pindang-otak-otak-singapore' => 'img/menu/pool/pindang-otak-otak-singapore.jpg',
            'pindang-brengkes-pindang-patin' => 'img/menu/pool/pindang-patin-juga.jpg',
            'pindang-brengkes-pindang-tulang' => 'img/menu/pool/pindang-tulang-juga.jpg',
            'snack-cakwe-biasa' => 'img/menu/pool/sarapan-pagi-cakwe.jpg',
            'snack-cakwe-isi-udang' => 'img/menu/pool/sarapan-pagi-cakwe.jpg',
            'snack-kentang-goreng' => 'img/menu/pool/sarapan-pagi-ubi-goreng.jpg',
            'snack-nugget' => 'img/menu/pool/sarapan-pagi-ubi-goreng.jpg',
            'snack-pisang-goreng' => 'img/menu/pool/sarapan-pagi-pisang-bakar-keju-coklat.jpg',
            'snack-sayap-ayam-bbq-isi-3' => 'img/menu/pool/sarapan-pagi-ubi-goreng.jpg',
            'snack-ubi-goreng' => 'img/menu/pool/sarapan-pagi-ubi-goreng.jpg',
            'sup-soto-rawon' => 'img/menu/pool/rawon.jpg',
            'sup-soto-soto-ayam' => 'img/menu/pool/soto-ayam.jpg',
            'sup-soto-soto-daging' => 'img/menu/pool/soto-daging.jpg',
            'sup-soto-sup-asparagus' => 'img/menu/pool/sop-ayam.jpg',
            'sup-soto-sup-ayam' => 'img/menu/pool/sop-ayam.jpg',
            'sup-soto-sup-daging' => 'img/menu/pool/sop-daging.jpg',
            'sup-soto-sup-jagung-ayam' => 'img/menu/pool/sop-ayam.jpg',
            'sup-soto-sup-tomyam' => 'img/menu/pool/sop-tomyam.jpg',
            'udang-udang-benang-mas' => 'img/menu/pool/udang-benang-mas.jpg',
            'udang-udang-lada-garam' => 'img/menu/pool/ayam-lada-garam.jpg',
            'udang-udang-mayones' => 'img/menu/pool/udang-mayones.jpg',
            'udang-udang-sambal-pete' => 'img/menu/pool/udang-sambal-pete.jpg',
            'udang-udang-saos-mentega' => 'img/menu/pool/udang-goreng-mentega.jpg',
            'udang-udang-saos-thai' => 'img/menu/pool/udang-saos-thai.jpg',
            'udang-udang-telor-asin' => 'img/menu/pool/udang-telor-asin.jpg',
        ];

        foreach ($map as $slug => $path) {
            MenuItem::where('slug', $slug)->update(['image_path' => $path]);
        }
    }

    public function down(): void
    {
        //
    }
};
